# Generated by Django 5.0.2 on 2024-04-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={},
        ),
        migrations.RenameField(
            model_name="match",
            old_name="player1_id",
            new_name="player1",
        ),
        migrations.RenameField(
            model_name="match",
            old_name="player2_id",
            new_name="player2",
        ),
    ]
