# Generated by Django 5.0.2 on 2024-05-01 18:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_match_winner"),
        ("users", "0006_alter_friendship_from_user_alter_friendship_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStat",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("wins_count", models.IntegerField(default=0)),
                ("losses_count", models.IntegerField(default=0)),
                ("rating", models.IntegerField(default=2000)),
                (
                    "local_play_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                (
                    "online_play_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("max_rating", models.IntegerField(default=0)),
                ("max_ball_speed", models.FloatField(default=0)),
                ("max_rally_cnt", models.IntegerField(default=0)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
