version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    container_name: nginx_container
    depends_on:
      - game
      - backend
    volumes:
      - ./FE:/usr/share/nginx/html/FE
    networks:
      - pong_net

  game:
    build: ./GAME
    container_name: game_container
    volumes:
      - ./GAME:/code
    env_file:
      - ./.env
    networks:
      - pong_net

  backend:
    build: ./BE
    container_name: backend_container
    depends_on:
      - postgresql
    volumes:
      - ./BE:/code
    env_file:
      - ./.env
    networks:
      - pong_net

  postgresql:
    image: postgres:alpine
    container_name: db_container
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - pong_net

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/postgresql
      o: bind

networks:
  pong_net:
    driver: bridge
