# Generated by Django 5.0.2 on 2024-03-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="", max_length=12, unique=True),
        ),
    ]
