# Generated by Django 5.0.2 on 2024-04-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_url",
            field=models.CharField(
                default="http://localhost:8000/api/profile/default.png", max_length=250
            ),
        ),
    ]
