# Generated by Django 5.0.2 on 2024-04-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_profile_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_url",
            field=models.CharField(default="/profile/default.png", max_length=250),
        ),
    ]
