# Generated by Django 5.0.2 on 2024-04-27 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile_url_friendship_user_friends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendship",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="user2",
        ),
        migrations.AddField(
            model_name="friendship",
            name="are_we_friend",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="friendship",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="friendship",
            name="from_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendship",
            name="to_user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
