# Generated by Django 5.0.2 on 2024-04-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_profile_url_friendship_user_friends"),
        ("users", "0005_friendship_alter_user_friends"),
    ]

    operations = []
