# Generated by Django 5.0.2 on 2024-05-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_friendship_from_user_alter_friendship_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("uploaded_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
